sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t rameshrn-dev/docker-react

script:
  - docker run -e CI=true rameshrn-dev/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1" 
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-730335491439"
  bucket_path: "frontend"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

