sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t rameshrn-dev/docker-react

script:
  - docker run -e CI=true rameshrn-dev/docker-react npm run test -- --coverage
