sudo: required
services:
    - docker

before_install:
    - docker build -t rameshrn/docker-react -f frontend/Dockerfile.dev .

script:
    - docker run rameshrn/docker-react npm run test -- --coverage

